# This is a basic workflow to help you get started with Actions

name: Build Rakudo Star for Windows

# Controls when the action will run.
# Triggers the workflow on push requests, new tag's or branches [with create] 
on: [workflow_dispatch]
#  [push, create]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Windows-latest has almost all reuirements to build rakudo-start-win
    # The only dependeny we need to install is the wixtoolset. We will use choco to do this
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup VS Dev Environment
        uses: seanmiddleditch/gha-setup-vsdevenv@v3
      - name: Force the wixtoolset installation
        run: choco install --yes --force --no-progress --limit-output --timeout 0 wixtoolset
      - name: Run the build-with-choco.ps1 script
        run: pwsh -command ".\$GITHUB_WORKSPACE\build-with-choco.ps1"
      - name: Upload output artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload output dirctory
          path: output/
          if-no-files-found: error
      - name: Release Rakudo Star - Windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: output/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
