# This is a basic workflow to help you get started with Actions

name: Test choco

# Controls when the action will run.
# Triggers the workflow on push requests, new tag's or branches
on:  [push, create]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  WixToolSet:
    # Windows-latest has almost all reuirements to build rakudo-start-win
    # The only dependeny we need to install is the wixtoolset. We will use choco to do this
    runs-on: windows-latest
    steps:
      - name: Force the wixtoolset installation
        run: choco install --yes --force --degub --no-progress --limit-output --timeout 0 wixtoolset
      - name: Show WixToolSet Path
        run: |
          (Get-Command "heat.exe" -ErrorAction Break).Path
          ls C:\ProgramData\chocolatey\bin
      - name: Try the choco action
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install --yes --force --degub --no-progress --limit-output --timeout 0 wixtoolset
      - name: Show WixToolSet Path again
        run: |
          (Get-Command "heat.exe" -ErrorAction Break).Path
          ls C:\ProgramData\chocolatey\bin
