# This is a basic workflow to help you get started with Actions

name: Test choco

# Controls when the action will run.
# Triggers the workflow on push requests, new tag's or branches
on:  push
#[push, create]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  WixToolSet:
    # Windows-latest has almost all reuirements to build rakudo-start-win
    # The only dependeny we need to install is the wixtoolset. We will use choco to do this
    runs-on: windows-latest
    steps:
      - name: Force the wixtoolset installation
        run: |
          choco install --yes --force --no-progress --timeout 0 wixtoolset
          echo "after_choco_install: $env:WIX"
      - name: Update the $env:PATH (shuoldn't this be done by choco install???)
        run: |
          $env:PATH = "C:\Program Files (x86)\WiX Toolset v3.11\bin;$env:PATH"
          [Environment]::SetEnvironmentVariable("Path", $env:PATH, "Machine")
          echo $env:Path
          ls "C:\Program Files (x86)\WiX Toolset v3.11\bin\heat.exe"
      - name: Show heat.exe Path
        run: |
          (Get-Command "heat.exe" -ErrorAction Break).Path
